version: '3'

services:
  nginx:
    build: .
    image: servercontainers/nginx
    restart: always
    environment:
      NGINX_CONFIG_registry: upstream docker-registry {server registry:5000;} server {server_name registry.example.com; include /etc/nginx/snippets/docker-registry-proxy.conf;}
      HTACCESS_ACCOUNT_bob: pa55word
    ports:
      - 80:80
      - 443:443
    networks:
      - registry-net

  registry:
    image: registry:2
    restart: always
    volumes:
      ./data:/var/lib/registry
    networks:
      - registry-net

networks:
  registry-net:
    driver: bridge
